# Numpy Arrays

In [1]:
my_list = [1, 2, 3]
print(my_list)

[1, 2, 3]


In [1]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,))

array([0., 0.])

In [13]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.zeros((1, 2))

array([[0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [20]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [21]:
np.linspace(0, 5, 20, endpoint=False)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

# Identity Matrix using Numpy

__Identity matrix is a 2-d matrix where the diangonal are ones and everything else are zeros__

In [22]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.05690323, 0.89831977, 0.3176544 , 0.29945568, 0.50880053])

In [24]:
np.random.rand(3,3)

array([[0.10139941, 0.53662242, 0.06503401],
       [0.72620117, 0.91421241, 0.74458396],
       [0.03094275, 0.19149588, 0.94274407]])

In [26]:
np.random.randint(4, 10)

7

In [27]:
np.random.randint(4, 10, 12)

array([8, 6, 6, 4, 8, 6, 9, 9, 4, 8, 6, 7])

In [28]:
np.random.randn(2)

array([-0.25780301,  0.67431896])

In [29]:
np.random.randn(4, 4)

array([[-1.46779148, -0.41068211, -0.73778061,  0.71178803],
       [-0.03755283, -0.4702095 , -0.55249367, -0.10623004],
       [ 0.61699927,  1.79796943,  1.13438105,  0.32218981],
       [-0.31957022, -1.13273121,  0.04138885,  0.15167047]])

In [30]:
np.random.randint(1, 100)

44

In [31]:
np.random.randint(1, 100, 10)

array([99, 18,  8, 34, 38, 69, 14, 31,  7, 83])

In [32]:
arr = np.random.randint(0, 50, 25)

In [33]:
arr

array([26, 17, 40, 43, 44, 49,  0, 45,  2, 46, 27, 12,  4, 12, 40, 47,  6,
       30, 10, 12, 20, 49,  8, 41, 38])

In [34]:
arr.reshape(5, 5)

array([[26, 17, 40, 43, 44],
       [49,  0, 45,  2, 46],
       [27, 12,  4, 12, 40],
       [47,  6, 30, 10, 12],
       [20, 49,  8, 41, 38]])

In [35]:
arr.reshape(3, 7)

ValueError: cannot reshape array of size 25 into shape (3,7)

In [36]:
arr

array([26, 17, 40, 43, 44, 49,  0, 45,  2, 46, 27, 12,  4, 12, 40, 47,  6,
       30, 10, 12, 20, 49,  8, 41, 38])

In [37]:
arr.max()

49

In [38]:
arr.min()

0

In [39]:
arr.argmax()

5

In [40]:
arr.argmin()

6

In [43]:
arr.shape

(25,)

In [46]:
arr = arr.reshape(5, 5)

In [47]:
arr

array([[26, 17, 40, 43, 44],
       [49,  0, 45,  2, 46],
       [27, 12,  4, 12, 40],
       [47,  6, 30, 10, 12],
       [20, 49,  8, 41, 38]])

In [48]:
arr.shape

(5, 5)

In [49]:
arr.dtype

dtype('int64')

# Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[6]

6

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

__Broadcasting in numpy__

In [9]:
my_list = [i for i in range(11)]

In [10]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
list_slice = my_list[:5]

In [15]:
list_slice

[0, 1, 2, 3, 4]

*Simple Python Lists* cannot be ***broadcast***.

In [14]:
list_slice[:] = 10

TypeError: can only assign an iterable

In [16]:
my_arr = np.arange(0, 11)

In [17]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
array_slice = my_arr[:5]

In [19]:
array_slice

array([0, 1, 2, 3, 4])

In [20]:
# If I broadcast to a slice from numpy array, the original array is affected too
array_slice[:3] = 50

In [21]:
array_slice

array([50, 50, 50,  3,  4])

In [22]:
my_arr

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

**The above proves that when we slice a numpy array, it does not create a separate array as created in Lists**   
**Instead a link to the original array is created, so when we *broadcast* value to the slice the original array is affected**   
**In order to, so that we get a copy of the original array and that the original array does not get modified on broadcasting we use the *copy()* method of the numpy array.**

In [23]:
my_arr_copy = my_arr.copy()

In [24]:
my_arr_copy

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
my_arr

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# broadcasting on my_arr_copy; it does not affect the original
my_arr_copy[3:] = 50

In [27]:
my_arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [28]:
my_arr

array([50, 50, 50,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing 2-D Array

In [29]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
print(arr_2d[0][0])
print(arr_2d[0][1])
print(arr_2d[0][2])

5
10
15


In [35]:
print(arr_2d[2,])

[35 40 45]


In [36]:
print(arr_2d[2, 0])
print(arr_2d[2, 1])
print(arr_2d[2, 2])

35
40
45


### Sub-Matrix from Matrix

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [42]:
arr_2d[1:, 1:2]

array([[25],
       [40]])

In [43]:
n1 = np.array([[10, 20, 30, 40, 50], [50, 60, 70, 80, 90], [15, 25, 35, 45, 55], [55, 65, 75, 85, 95]])

In [44]:
n1

array([[10, 20, 30, 40, 50],
       [50, 60, 70, 80, 90],
       [15, 25, 35, 45, 55],
       [55, 65, 75, 85, 95]])

In [45]:
n1[:1,]

array([[10, 20, 30, 40, 50]])

In [46]:
n1[:2, 2:]

array([[30, 40, 50],
       [70, 80, 90]])

In [47]:
n1[2:, :2]

array([[15, 25],
       [55, 65]])

### Conditional Selection

In [48]:
n2 = np.arange(0, 11)

In [49]:
n2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_n2 = n2 > 5

In [51]:
bool_n2

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [52]:
n2(bool_n2)

TypeError: 'numpy.ndarray' object is not callable

In [53]:
n2[bool_n2]

array([ 6,  7,  8,  9, 10])

In [54]:
n2[n2 > 5]

array([ 6,  7,  8,  9, 10])

In [55]:
n2[n2<3]

array([0, 1, 2])

In [56]:
n3 = np.arange(50).reshape(5, 10)

In [57]:
n3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
n3[1:3,5:7]

array([[15, 16],
       [25, 26]])

In [60]:
n3[4:, 8:]

array([[48, 49]])

# Numpy Operations

* __Array with Array__
* __Array with Scalers__
* __Universal Array functions__

In [61]:
import numpy as np

In [62]:
arr = np.arange(0, 11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

__Scalers get broadcasted to every elements in the array__

In [67]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [68]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [71]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
1 / 0

ZeroDivisionError: division by zero

In [74]:
arr / arr

/home/ubuntu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
1 / arr

/home/ubuntu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [76]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [77]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Universal Array Functions

In [78]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [80]:
np.max(arr)

10

In [82]:
arr.max()

10

In [83]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [84]:
np.log(arr)

/home/ubuntu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])